USE juegosolimpicos1;

CREATE VIEW medaloro_athlete AS select a.name as name, h.id_medal AS medal_oro FROM hechosathlete h 
LEFT JOIN athlete a ON h.id_athlete = a.id_athlete WHERE id_medal = 2;

SELECT * FROM medaloro_athlete;


CREATE VIEW MEDALOROCOUNT_ATHLETE AS SELECT A.NAME, A.AGE, COUNT(H.ID_MEDAL) AS COUNT_MEDAL_ORO FROM ATHLETE A 
LEFT JOIN HECHOSATHLETE H ON A.ID_ATHLETE=H.ID_ATHLETE WHERE ID_MEDAL=2 
GROUP BY H.ID_ATHLETE ORDER BY ID_MEDAL DESC LIMIT 10;

SELECT * FROM MEDALOROCOUNT_ATHLETE;

CREATE VIEW MEDALBRONZE_ATHLETE AS SELECT A.NAME, A.AGE, H.ID_MEDAL AS MEDAL FROM ATHLETE A 
LEFT JOIN HECHOSATHLETE H ON A.ID_ATHLETE=H.ID_ATHLETE 
WHERE AGE >= 25 AND ID_MEDAL = 3 GROUP BY H.ID_ATHLETE ORDER BY ID_MEDAL DESC LIMIT 5;

SELECT * FROM MEDALBRONZE_ATHLETE;

CREATE VIEW CITYLONDON_ATHLETE AS SELECT A.NAME, S.SPORT, C.CITY, H.ID_MEDAL AS MEDAL, N.NOC FROM HECHOSATHLETE H 
LEFT JOIN ATHLETE A ON H.ID_ATHLETE=A.ID_ATHLETE 
LEFT JOIN SPORT S ON H.ID_SPORT= S.ID_SPORT
LEFT JOIN CITY C ON H.ID_CITY=C.ID_CITY
LEFT JOIN NOC N ON H.ID_NOC=N.ID_NOC
WHERE CITY LIKE 'LONDON'GROUP BY H.ID_ATHLETE LIMIT 3;

SELECT * FROM CITYLONDON_ATHLETE;

CREATE VIEW HOCKEY_ATHLETE AS SELECT A.NAME, S.SPORT, G.YEAR, G.SEASON, H.ID_MEDAL, M.MEDAL FROM HECHOSATHLETE H 
LEFT JOIN ATHLETE A ON H.ID_ATHLETE=A.ID_ATHLETE
LEFT JOIN GAMES G ON H.ID_GAMES=G.ID_GAMES
LEFT JOIN SPORT S ON H.ID_SPORT=S.ID_SPORT
LEFT JOIN MEDAL M ON H.ID_MEDAL=M.ID_MEDAL
WHERE SPORT LIKE 'HOCKEY';

SELECT * FROM HOCKEY_ATHLETE;

CREATE VIEW GAMESSUMMER_ATHLETE AS SELECT DISTINCT A.NAME, G.SEASON, G.YEAR FROM HECHOSATHLETE H 
LEFT JOIN ATHLETE A ON H.ID_ATHLETE=A.ID_ATHLETE
LEFT JOIN GAMES G ON H.ID_GAMES=G.ID_GAMES
WHERE G.SEASON LIKE 'SUMMER' GROUP BY H.ID_ATHLETE ORDER BY YEAR;

SELECT * FROM GAMESSUMMER_ATHLETE;

