USE juegosolimpicos;


SELECT * FROM city;


START TRANSACTION;
INSERT INTO CITY VALUE(43, 'Colombia');
INSERT INTO CITY VALUE(44, 'Argentina');
INSERT INTO CITY VALUE(45, 'Mexico');
ROLLBACK;
COMMIT;


START TRANSACTION;
DELETE FROM CITY WHERE id_city=43;
DELETE FROM CITY WHERE id_city=44;
DELETE FROM CITY WHERE id_city=45;
ROLLBACK;
COMMIT;


SELECT * FROM athlete;
START TRANSACTION;
INSERT INTO athlete VALUES (DEFAULT, 'ana', 'F', 31, 160, 48);
INSERT INTO athlete VALUES (DEFAULT, 'pedro', 'M', 41, 190, 88);
INSERT INTO athlete VALUES (DEFAULT, 'sara', 'F', 21, 189, 68);
INSERT INTO athlete VALUES (DEFAULT, 'ana', 'F', 31, 160, 48);
SAVEPOINT INSERCION_1_4;
INSERT INTO athlete VALUES (DEFAULT, 'angie', 'F', 41, 190, 88);
INSERT INTO athlete VALUES (DEFAULT, 'natalia', 'F', 21, 189, 68);
INSERT INTO athlete VALUES (DEFAULT, 'leonardo', 'M', 41, 190, 88);
INSERT INTO athlete VALUES (DEFAULT, 'juliana', 'F', 21, 189, 68);
SAVEPOINT INSERCION_5_8;
##ROLLBACK;
-- RELEASE SAVEPOINT INSERCION_1_4;
##COMMIT;

