DELIMITER ##
CREATE PROCEDURE ORDENAMIENTO_RANGO_EDAD1 (IN CANT_EDAD INT, IN CANT_EDAD2 INT, IN ORDEN BOOLEAN)
BEGIN 
	SET @CANTIDAD_AGE = (SELECT COUNT(*) FROM ATHLETE WHERE AGE BETWEEN CANT_EDAD AND CANT_EDAD2);
	IF@CANTIDAD_AGE <> ''  AND ORDEN = 1 THEN 
		SELECT * FROM ATHLETE WHERE AGE BETWEEN CANT_EDAD AND CANT_EDAD2 ORDER BY AGE ASC;
	ELSEIF @CANTIDAD_AGE <> ''  AND ORDEN = 0 THEN 
		SELECT * FROM ATHLETE WHERE AGE BETWEEN CANT_EDAD AND CANT_EDAD2 ORDER BY AGE DESC;
	ELSEIF @CANTIDAD_AGE <> '' AND orden NOT IN (0,1) THEN
		SET @ordenar = 'No válido';
		SELECT 'Parámetro de ordenamiento ingresado no válido' AS Mensaje;
	ELSEIF @CANTIDAD_AGE = 0 THEN
         SELECT 'NO EXISTE' AS MENSAJE;
		END IF;
    
END ##
DELIMITER ;

CALL ORDENAMIENTO_RANGO_EDAD1(20, 40, 1);
CALL ORDENAMIENTO_RANGO_EDAD1(20, 40, 0);
CALL ORDENAMIENTO_RANGO_EDAD1(1, 4, 0);
CALL ORDENAMIENTO_RANGO_EDAD1(22, 40, 5);


##DROP PROCEDURE IF EXISTS DELET_HECHO;
SELECT * FROM hechosathlete;

DELIMITER ##
CREATE PROCEDURE INSE_HECHO (IN PARAM_ID_HECHO INT, IN PARAM_ID_ATHLETE INT, IN PARAM_ID_YEAR INT, IN PARAM_ID_SEASON INT, IN PARAM_ID_NOC INT, IN PARAM_ID_GAMES INT, IN PARAM_ID_CITY INT, IN PARAM_ID_SPORT INT, IN PARAM_ID_EVENT INT, IN PARAM_ID_MEDAL INT)
BEGIN 
	 INSERT INTO HECHOSATHLETE(ID_HECHOS, ID_ATHLETE, ID_YEAR, ID_SEASON, ID_NOC, ID_GAMES, ID_CITY, ID_SPORT, ID_EVENT, ID_MEDAL) values(PARAM_ID_HECHO, PARAM_ID_ATHLETE, PARAM_ID_YEAR, PARAM_ID_SEASON, PARAM_ID_NOC, PARAM_ID_GAMES, PARAM_ID_CITY, PARAM_ID_SPORT, PARAM_ID_EVENT, PARAM_ID_MEDAL);
END ##
DELIMITER ;
CALL INSE_HECHO (100, 2, 32, 1, 1, 34, 1, 3, 1, 1);

SELECT * FROM hechosathlete;

DELIMITER ## 
CREATE PROCEDURE DELET_HECHO (IN PARAM_ID_REG INT)
BEGIN 
	DELETE FROM HECHOSATHLETE WHERE ID_HECHOS = PARAM_ID_REG;
END ##
DELIMITER ;

CALL DELET_HECHO (100);

SELECT * FROM hechosathlete;



